[package]
name = "vuzt_slint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
slint = { version = "1.5", features = ["backend-android-activity-05", "compat-1-2"] }
android-activity = "0.5"
log = "0.4"
android_logger = "0.13"

[package.metadata.android]
package = "com.cak.vuzt"
label = "Vuzt Slint"
build_targets = ["aarch64-linux-android"]
target_sdk_version = 30
min_sdk_version = 21

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
