[package]
name = "cakru_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
# OPTIMASI: Mematikan default-features agar compiler hanya fokus merakit biner untuk Android
slint = { version = "1.16", default-features = false, features = ["backend-android-activity-06", "compat-1-2"] }
log = "0.4"
android_logger = "0.13"

[build-dependencies]
slint-build = "1.16"

[package.metadata.android]
package = "com.cak.cakru"
label = "Cakru App"
build_targets = ["aarch64-linux-android"]
min_sdk_version = 21
# OPTIMASI: Menaikkan Target SDK agar sesuai dengan standar Android modern (meningkatkan akurasi safe-area & keyboard)
target_sdk_version = 34
resources = "android-res/res"

[package.metadata.android.application]
icon = "@mipmap/ic_launcher"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

# STRATEGI OPTIMASI UKURAN BINER (Sudah Sangat Bagus)
[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package."*"]
opt-level = "z"
strip = true

[package.metadata.android.signing.release]
path = "temp.keystore"
keystore_password = "temp123"
key_alias = "temp"
key_password = "temp123"
