[package]
name = "vuzt_slint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
slint = { version = "1.16", features = ["backend-android-activity-06", "compat-1-2"] }
android-activity = "0.6"
log = "0.4"
android_logger = "0.13"

[build-dependencies]
slint-build = "1.16"

[package.metadata.android]
package = "com.cak.vuzt"
label = "Vuzt Slint"
build_targets = ["aarch64-linux-android"]
target_sdk_version = 30
min_sdk_version = 21

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.signing.release]
path = "debug.keystore"
keystore_password = "android"
key_alias = "androiddebugkey"
key_password = "android"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
