import { VerticalBox, Button, LineEdit } from "std-widgets.slint";

component App {
    in-out property <string> name-input: "";
    in-out property <string> message: "";
    callback say-hello;
    
    VerticalBox {
        alignment: center;
        padding: 20px;
        spacing: 20px;
        
        Text {
            text: "Masukkan Nama Anda";
            font-size: 24px;
            color: #2196f3;
        }
        
        LineEdit {
            placeholder-text: "Ketik nama di sini...";
            text: name-input;
            edited => { name-input = self.text; }
        }
        
        Button {
            text: "Sapa Saya";
            clicked => { say-hello(); }
        }
        
        Text {
            text: message;
            font-size: 20px;
            color: #4caf50;
            visible: message != "";
        }
    }
}

export { App }
