import { LineEdit } from "std-widgets.slint";

export component CakruInputField inherits VerticalLayout {
    in property <string> label-text;
    in property <string> placeholder;
    in property <bool> is-dark; // Menerima status tema
    in-out property <string> text <=> input.text;

    spacing: 5px;

    Text {
        text: root.label-text;
        font-size: 14px;
        // Teks label: Gelap di light mode, Terang di dark mode
        color: root.is-dark ? #b0b0b0 : #555555;
        horizontal-alignment: left;
    }

    input := LineEdit {
        placeholder-text: root.placeholder;
        accessible-label: root.label-text;
    }
}

export component CakruButton inherits Rectangle {
    in property <string> text;
    in property <bool> is-dark; // Menerima status tema
    callback clicked;

    border-width: 1px;
    border-color: root.is-dark ? #cccccc40 : #00000020;
    border-radius: 5px;
    
    // Warna tombol menyesuaikan tema kaca gelap / terang
    background: touch-area.has-hover ? 
        (root.is-dark ? rgba(255, 255, 255, 0.15) : rgba(0, 0, 0, 0.15)) : 
        (root.is-dark ? rgba(255, 255, 255, 0.08) : rgba(0, 0, 0, 0.05));
    
    drop-shadow-color: rgba(0, 0, 0, 0.15);
    drop-shadow-blur: touch-area.has-hover ? 16px : 0px;

    padding-top: touch-area.has-hover ? 10px : 20px;
    padding-bottom: touch-area.has-hover ? 30px : 20px;
    
    animate background, drop-shadow-blur, padding-top, padding-bottom {
        duration: 300ms;
        easing: ease-in-out;
    }

    touch-area := TouchArea {
        clicked => { root.clicked(); }
    }

    HorizontalLayout {
        alignment: center;
        Text {
            text: root.text;
            // Teks tombol: Putih di dark mode, Biru Gelap di light mode
            color: root.is-dark ? #ffffff : #2196f3;
            font-size: 22px;
            font-weight: 700;
        }
    }
}
