name: Build Cakru APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-binstall
      run: |
        WANTED_VERSION="v1.10.1"
        ARCH="x86_64-unknown-linux-musl"
        wget https://github.com/cargo-bins/cargo-binstall/releases/download/${WANTED_VERSION}/cargo-binstall-${ARCH}.tgz
        tar -xvf cargo-binstall-${ARCH}.tgz
        mv cargo-binstall ~/.cargo/bin/

    - name: Install cargo-apk
      run: cargo binstall cargo-apk -y

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK & Platforms
      run: |
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-30" "platforms;android-34" "ndk;26.1.10909125"
        echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/26.1.10909125" >> $GITHUB_ENV

    # TRIK JITU: Buat file debug.keystore tiruan tepat di root folder proyek agar cargo-apk tidak rewel
    - name: Generate Dummy Debug Keystore
      run: |
        keytool -genkey -v \
          -keystore debug.keystore \
          -alias androiddebugkey \
          -storepass android \
          -keypass android \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    - name: Build release APK
      run: cargo apk build --release

    - name: Remove unaligned APK
      run: rm -f target/release/apk/*-unaligned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cakru-app
        path: target/release/apk/*.apk
